### ISSUE TITLE
Excellent! Very helpful! Thank you Matthew Wright.

### ISSUE THREAD

**Issue by goodgoodwish** [farskipper/vanilla-js-apollo-graphql-full-stack-playground#1]
My working version is

import { gql } from 'react-apollo'

in place of

import { gql } from "graphql-tag"
or
var gql = require("graphql-tag");

**Comment by farskipper** [comment]
Yeah, no problem. So `react-apollo` wraps `graphql-tag` as [a dependency](https://github.com/apollographql/react-apollo/blob/master/package.json#L153) (and exported [here](https://github.com/apollographql/react-apollo/blob/master/src/browser.ts#L20)) so both _should_ work. I just wanted this gitrepo to be bare bones without `react` so it's easy to see just graphql. And then you can add react or whatever on top of it.

**Comment by goodgoodwish** [comment]
Thanks for the quick and complete elaboration. Now I know why graphql-tag.

Do you happen to have a tech blog and some other channels?

**Comment by farskipper** [comment]
No blog yet, just stuff on github. Is this your blog: http://mujiang.blogspot.com/ ? nice
